### ISSUE TITLE
FileNotFoundError in converting states for PickSingleEGAD

### ISSUE THREAD

**Issue by ZhuFengdaaa** [haosulab/ManiSkill2-Learn#3]
I run

```
python3.8 ./tools/convert_state.py --num-procs 10 --env-name PickSingleEGAD-v0 --traj-name /ManiSkill2-data/rigid_body_envs/PickSingleEGAD-v0/trajectory.h5 --json-name /ManiSkill2-data/rigid_body_envs/PickSingleEGAD-v0/trajectory.json --output-name trajectory_pcd.h5
```

And I get this log: 

```
FileNotFoundError: /ManiSkill2/mani_skill2/assets/mani_skill2_egad/egad_train_set_coacd or /ManiSkill2/mani_skill2/assets/mani_skill2_egad/egad_train_set is not found. Please download EGAD models first.
Traceback (most recent call last):
  File "./tools/convert_state.py", line 230, in <module>
    main()
  File "./tools/convert_state.py", line 222, in main
    merge_h5_trajectory(files, args.output_name)
  File "/ManiSkill2-Learn/maniskill2_learn/utils/file/record_utils.py", line 265, in merge_h5_trajectory
    h5 = h5py.File(h5_file, "r")
  File "/home/anaconda3/envs/mani_skill2/lib/python3.8/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/anaconda3/envs/mani_skill2/lib/python3.8/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/tmp/0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by xuanlinli17** [comment]
```
FileNotFoundError: /ManiSkill2/mani_skill2/assets/mani_skill2_egad/egad_train_set_coacd or /ManiSkill2/mani_skill2/assets/mani_skill2_egad/egad_train_set is not found. Please download EGAD models first.
```

This is the actual error. Please download EGAD models first (following instructions in ManiSkill2)

**Comment by xuanlinli17** [comment]
Enter ManiSkill2 (not ManiSkill2-Learn) directory, run

`python tools/download.py --uid all`

**Comment by xuanlinli17** [comment]
Closed as completed.
